// Code generated by go-swagger; DO NOT EDIT.

package generator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/myjupyter/testifai/src/frontend/client/models"
)

// NewPostGenerateParams creates a new PostGenerateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostGenerateParams() *PostGenerateParams {
	return &PostGenerateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostGenerateParamsWithTimeout creates a new PostGenerateParams object
// with the ability to set a timeout on a request.
func NewPostGenerateParamsWithTimeout(timeout time.Duration) *PostGenerateParams {
	return &PostGenerateParams{
		timeout: timeout,
	}
}

// NewPostGenerateParamsWithContext creates a new PostGenerateParams object
// with the ability to set a context for a request.
func NewPostGenerateParamsWithContext(ctx context.Context) *PostGenerateParams {
	return &PostGenerateParams{
		Context: ctx,
	}
}

// NewPostGenerateParamsWithHTTPClient creates a new PostGenerateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostGenerateParamsWithHTTPClient(client *http.Client) *PostGenerateParams {
	return &PostGenerateParams{
		HTTPClient: client,
	}
}

/*
PostGenerateParams contains all the parameters to send to the API endpoint

	for the post generate operation.

	Typically these are written to a http.Request.
*/
type PostGenerateParams struct {

	/* Request.

	   Реквест
	*/
	Request *models.ServerRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post generate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostGenerateParams) WithDefaults() *PostGenerateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post generate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostGenerateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post generate params
func (o *PostGenerateParams) WithTimeout(timeout time.Duration) *PostGenerateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post generate params
func (o *PostGenerateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post generate params
func (o *PostGenerateParams) WithContext(ctx context.Context) *PostGenerateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post generate params
func (o *PostGenerateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post generate params
func (o *PostGenerateParams) WithHTTPClient(client *http.Client) *PostGenerateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post generate params
func (o *PostGenerateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post generate params
func (o *PostGenerateParams) WithRequest(request *models.ServerRequest) *PostGenerateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post generate params
func (o *PostGenerateParams) SetRequest(request *models.ServerRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostGenerateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
