// Code generated by go-swagger; DO NOT EDIT.

package generator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/myjupyter/testifai/src/frontend/client/models"
)

// PostGenerateReader is a Reader for the PostGenerate structure.
type PostGenerateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGenerateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostGenerateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /generate] PostGenerate", response, response.Code())
	}
}

// NewPostGenerateOK creates a PostGenerateOK with default headers values
func NewPostGenerateOK() *PostGenerateOK {
	return &PostGenerateOK{}
}

/*
PostGenerateOK describes a response with status code 200, with default header values.

OK
*/
type PostGenerateOK struct {
	Payload *models.ServerResponse
}

// IsSuccess returns true when this post generate o k response has a 2xx status code
func (o *PostGenerateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post generate o k response has a 3xx status code
func (o *PostGenerateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post generate o k response has a 4xx status code
func (o *PostGenerateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post generate o k response has a 5xx status code
func (o *PostGenerateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post generate o k response a status code equal to that given
func (o *PostGenerateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post generate o k response
func (o *PostGenerateOK) Code() int {
	return 200
}

func (o *PostGenerateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /generate][%d] postGenerateOK %s", 200, payload)
}

func (o *PostGenerateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /generate][%d] postGenerateOK %s", 200, payload)
}

func (o *PostGenerateOK) GetPayload() *models.ServerResponse {
	return o.Payload
}

func (o *PostGenerateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
