// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServerResponse server response
//
// swagger:model server.Response
type ServerResponse struct {

	// generated
	Generated *ServerGenerated `json:"generated,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this server response
func (m *ServerResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGenerated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerResponse) validateGenerated(formats strfmt.Registry) error {
	if swag.IsZero(m.Generated) { // not required
		return nil
	}

	if m.Generated != nil {
		if err := m.Generated.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("generated")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("generated")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this server response based on the context it is used
func (m *ServerResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGenerated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerResponse) contextValidateGenerated(ctx context.Context, formats strfmt.Registry) error {

	if m.Generated != nil {

		if swag.IsZero(m.Generated) { // not required
			return nil
		}

		if err := m.Generated.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("generated")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("generated")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerResponse) UnmarshalBinary(b []byte) error {
	var res ServerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
