// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServerRequest server request
//
// swagger:model server.Request
type ServerRequest struct {

	// context
	Context *ServerGenerateContext `json:"context,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// testifai
	Testifai *ServerTestifai `json:"testifai,omitempty"`
}

// Validate validates this server request
func (m *ServerRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTestifai(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerRequest) validateContext(formats strfmt.Registry) error {
	if swag.IsZero(m.Context) { // not required
		return nil
	}

	if m.Context != nil {
		if err := m.Context.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("context")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("context")
			}
			return err
		}
	}

	return nil
}

func (m *ServerRequest) validateTestifai(formats strfmt.Registry) error {
	if swag.IsZero(m.Testifai) { // not required
		return nil
	}

	if m.Testifai != nil {
		if err := m.Testifai.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("testifai")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("testifai")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this server request based on the context it is used
func (m *ServerRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateContext(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTestifai(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServerRequest) contextValidateContext(ctx context.Context, formats strfmt.Registry) error {

	if m.Context != nil {

		if swag.IsZero(m.Context) { // not required
			return nil
		}

		if err := m.Context.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("context")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("context")
			}
			return err
		}
	}

	return nil
}

func (m *ServerRequest) contextValidateTestifai(ctx context.Context, formats strfmt.Registry) error {

	if m.Testifai != nil {

		if swag.IsZero(m.Testifai) { // not required
			return nil
		}

		if err := m.Testifai.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("testifai")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("testifai")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerRequest) UnmarshalBinary(b []byte) error {
	var res ServerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
