// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServerGenerateContext server generate context
//
// swagger:model server.GenerateContext
type ServerGenerateContext struct {

	// external import
	ExternalImport []string `json:"external_import"`

	// package name
	PackageName string `json:"package_name,omitempty"`

	// platform
	Platform string `json:"platform,omitempty"`

	// user code
	UserCode string `json:"user_code,omitempty"`

	// user code context
	UserCodeContext string `json:"user_code_context,omitempty"`
}

// Validate validates this server generate context
func (m *ServerGenerateContext) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this server generate context based on context it is used
func (m *ServerGenerateContext) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerGenerateContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerGenerateContext) UnmarshalBinary(b []byte) error {
	var res ServerGenerateContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
