// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServerTestifai server testifai
//
// swagger:model server.Testifai
type ServerTestifai struct {

	// test type
	TestType string `json:"test_type,omitempty"`
}

// Validate validates this server testifai
func (m *ServerTestifai) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this server testifai based on context it is used
func (m *ServerTestifai) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerTestifai) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerTestifai) UnmarshalBinary(b []byte) error {
	var res ServerTestifai
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
