// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServerGenerated server generated
//
// swagger:model server.Generated
type ServerGenerated struct {

	// test code
	TestCode string `json:"test_code,omitempty"`
}

// Validate validates this server generated
func (m *ServerGenerated) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this server generated based on context it is used
func (m *ServerGenerated) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerGenerated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerGenerated) UnmarshalBinary(b []byte) error {
	var res ServerGenerated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
