// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "iauglov@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/generate": {
            "post": {
                "description": "Метод генерирует и возвращает тесты",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Generator"
                ],
                "summary": "Generate tests",
                "parameters": [
                    {
                        "description": "Реквест",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "server.GenerateContext": {
            "type": "object",
            "properties": {
                "external_import": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "package_name": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                },
                "user_code": {
                    "type": "string"
                },
                "user_code_context": {
                    "type": "string"
                }
            }
        },
        "server.Generated": {
            "type": "object",
            "properties": {
                "test_code": {
                    "type": "string"
                }
            }
        },
        "server.Request": {
            "type": "object",
            "properties": {
                "context": {
                    "$ref": "#/definitions/server.GenerateContext"
                },
                "id": {
                    "type": "string"
                },
                "testifai": {
                    "$ref": "#/definitions/server.Testifai"
                }
            }
        },
        "server.Response": {
            "type": "object",
            "properties": {
                "generated": {
                    "$ref": "#/definitions/server.Generated"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "server.Testifai": {
            "type": "object",
            "properties": {
                "test_type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Testifai backend",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
