basePath: /
definitions:
  server.GenerateContext:
    properties:
      external_import:
        items:
          type: string
        type: array
      package_name:
        type: string
      platform:
        type: string
      user_code:
        type: string
      user_code_context:
        type: string
    type: object
  server.Generated:
    properties:
      test_code:
        type: string
    type: object
  server.Request:
    properties:
      context:
        $ref: '#/definitions/server.GenerateContext'
      id:
        type: string
      testifai:
        $ref: '#/definitions/server.Testifai'
    type: object
  server.Response:
    properties:
      generated:
        $ref: '#/definitions/server.Generated'
      id:
        type: string
    type: object
  server.Testifai:
    properties:
      test_type:
        type: string
    type: object
info:
  contact:
    email: iauglov@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  termsOfService: http://swagger.io/terms/
  title: Testifai backend
  version: "1.0"
paths:
  /generate:
    post:
      consumes:
      - application/json
      description: Метод генерирует и возвращает тесты
      parameters:
      - description: Реквест
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Response'
      summary: Generate tests
      tags:
      - Generator
swagger: "2.0"
